export const SERVICE_CATEGORIES = ['Digital Marketing', 'Web Development', 'App Development', 'Automation & AI'];

export const SERVICES = {
  'Digital Marketing': [
    {
      id: 'dm_social',
      name: 'Social Media Marketing',
      description: 'Strategic social media management across platforms (Instagram, Facebook, LinkedIn)',
      sacCode: '998363',
      basePrice: 15000,
      priceType: 'monthly',
      durations: [3, 6, 12],
      deliverables: [
        '30 posts/month per platform',
        'Content calendar',
        'Engagement management',
        'Monthly analytics report',
        'Story/Reel creation',
      ],
    },
    {
      id: 'dm_ads',
      name: 'Performance Ads (Meta/Google)',
      description: 'Data-driven paid advertising campaigns optimized for ROI',
      sacCode: '998363',
      basePrice: 20000,
      priceType: 'monthly',
      durations: [3, 6, 12],
      note: 'Ad spend budget separate',
      deliverables: [
        'Campaign strategy & setup',
        'Ad creatives (5 per month)',
        'A/B testing',
        'Weekly performance reports',
        'Audience targeting & optimization',
      ],
    },
    {
      id: 'dm_seo',
      name: 'SEO (Search Engine Optimization)',
      description: 'Organic search ranking improvement through technical & content SEO',
      sacCode: '998363',
      basePrice: 12000,
      priceType: 'monthly',
      durations: [3, 6, 12],
      deliverables: [
        'On-page SEO optimization',
        'Keyword research & strategy',
        '4 SEO blog articles/month',
        'Backlink building',
        'Monthly ranking report',
      ],
    },
    {
      id: 'dm_content',
      name: 'Content Creation',
      description: 'Professional content production for digital channels',
      sacCode: '998363',
      basePrice: 10000,
      priceType: 'monthly',
      durations: [3, 6, 12],
      deliverables: [
        'Graphic design (10 creatives/month)',
        'Copywriting for social',
        'Email newsletter content',
        'Blog articles',
        'Video scripts',
      ],
    },
    {
      id: 'dm_branding',
      name: 'Branding',
      description: 'Complete brand identity design and guidelines',
      sacCode: '998363',
      basePrice: 35000,
      priceType: 'onetime',
      durations: null,
      deliverables: [
        'Logo design (3 concepts)',
        'Brand color palette',
        'Typography system',
        'Brand guidelines document',
        'Business card & stationery design',
      ],
    },
    {
      id: 'dm_full',
      name: 'Full Marketing Package',
      description: 'Complete digital marketing solution — social, ads, SEO, content',
      sacCode: '998363',
      basePrice: 45000,
      priceType: 'monthly',
      durations: [3, 6, 12],
      recommended: true,
      deliverables: [
        'Social media management (2 platforms)',
        'Performance ads management',
        'SEO optimization',
        'Content creation (20 pieces)',
        'Monthly strategy meeting',
        'Dedicated account manager',
      ],
    },
  ],

  'Web Development': [
    {
      id: 'web_landing',
      name: 'Landing Page',
      description: 'High-converting single-page website optimized for leads',
      sacCode: '998314',
      basePrice: 15000,
      priceType: 'onetime',
      durations: null,
      defaultPages: 1,
      deliverables: [
        '1 responsive page',
        'Lead capture form',
        'Mobile optimized',
        'SEO meta setup',
        '2 rounds of revisions',
      ],
    },
    {
      id: 'web_business',
      name: 'Business Website',
      description: 'Professional multi-page website for your business',
      sacCode: '998314',
      basePrice: 35000,
      priceType: 'onetime',
      durations: null,
      defaultPages: 5,
      deliverables: [
        'Up to 5 pages',
        'Contact form integration',
        'Google Maps integration',
        'Mobile responsive',
        'Basic SEO setup',
        '3 rounds of revisions',
      ],
    },
    {
      id: 'web_ecommerce',
      name: 'E-Commerce Website',
      description: 'Full-featured online store with payment gateway',
      sacCode: '998314',
      basePrice: 75000,
      priceType: 'onetime',
      durations: null,
      defaultPages: 10,
      deliverables: [
        'Product catalog (up to 100 products)',
        'Payment gateway integration',
        'Order management',
        'Cart & checkout',
        'Admin panel',
        'Mobile app-like experience',
      ],
    },
    {
      id: 'web_custom',
      name: 'Custom Website',
      description: 'Fully custom-built web application',
      sacCode: '998314',
      basePrice: 120000,
      priceType: 'onetime',
      durations: null,
      defaultPages: 15,
      deliverables: [
        'Custom design & development',
        'Database integration',
        'User authentication',
        'Admin dashboard',
        'API integrations',
        '6 months free support',
      ],
    },
    {
      id: 'web_maintenance',
      name: 'Website Maintenance',
      description: 'Monthly website updates, security & performance',
      sacCode: '998314',
      basePrice: 5000,
      priceType: 'monthly',
      durations: [3, 6, 12],
      deliverables: [
        'Monthly content updates',
        'Security monitoring',
        'Performance optimization',
        'Uptime monitoring',
        'Backup management',
      ],
    },
  ],

  'App Development': [
    {
      id: 'app_android',
      name: 'Android App',
      description: 'Native/cross-platform Android application',
      sacCode: '998314',
      tiers: {
        Basic: { price: 75000, features: 'Up to 5 screens, basic features' },
        Advanced: { price: 150000, features: 'Up to 15 screens, API integrations' },
        Premium: { price: 300000, features: 'Unlimited screens, full custom features' },
      },
      priceType: 'onetime',
      deliverables: {
        Basic: ['5 screens', 'User auth', 'Push notifications', 'Play Store deployment'],
        Advanced: ['15 screens', 'API integration', 'Payment gateway', 'Analytics', 'Admin panel'],
        Premium: ['Custom features', 'Real-time sync', 'AI features', 'Full backend', '1 year support'],
      },
    },
    {
      id: 'app_ios',
      name: 'iOS App',
      description: 'Native/cross-platform iOS application',
      sacCode: '998314',
      tiers: {
        Basic: { price: 85000, features: 'Up to 5 screens, basic features' },
        Advanced: { price: 175000, features: 'Up to 15 screens, API integrations' },
        Premium: { price: 350000, features: 'Unlimited screens, full custom features' },
      },
      priceType: 'onetime',
      deliverables: {
        Basic: ['5 screens', 'User auth', 'Push notifications', 'App Store deployment'],
        Advanced: ['15 screens', 'API integration', 'Payment gateway', 'Analytics', 'Admin panel'],
        Premium: ['Custom features', 'Real-time sync', 'AI features', 'Full backend', '1 year support'],
      },
    },
    {
      id: 'app_both',
      name: 'Android + iOS App',
      description: 'Cross-platform app for both Android and iOS',
      sacCode: '998314',
      tiers: {
        Basic: { price: 140000, features: 'Up to 5 screens, both platforms' },
        Advanced: { price: 300000, features: 'Up to 15 screens, full features' },
        Premium: { price: 600000, features: 'Unlimited, enterprise grade' },
      },
      priceType: 'onetime',
      recommended: true,
      deliverables: {
        Basic: ['5 screens', 'Both platforms', 'User auth', 'Store deployment'],
        Advanced: ['15 screens', 'API integration', 'Payment gateway', 'Admin panel', 'Analytics'],
        Premium: ['Unlimited screens', 'AI features', 'Real-time', 'Full backend', '1 year support'],
      },
    },
    {
      id: 'app_admin',
      name: 'Admin Panel',
      description: 'Web-based admin dashboard for app management',
      sacCode: '998314',
      basePrice: 25000,
      priceType: 'onetime',
      deliverables: ['User management', 'Content management', 'Analytics dashboard', 'Reports'],
    },
    {
      id: 'app_uiux',
      name: 'UI/UX Design',
      description: 'Premium app design with Figma prototypes',
      sacCode: '998314',
      basePrice: 30000,
      priceType: 'onetime',
      deliverables: ['Wireframes', 'High-fidelity designs', 'Prototype', 'Design system', 'Developer handoff'],
    },
    {
      id: 'app_maintenance',
      name: 'App Maintenance',
      description: 'Monthly app updates, bug fixes & support',
      sacCode: '998314',
      basePrice: 8000,
      priceType: 'monthly',
      durations: [3, 6, 12],
      deliverables: ['Bug fixes', 'OS compatibility updates', 'Performance optimization', 'Monthly report'],
    },
  ],

  'Automation & AI': [
    {
      id: 'auto_whatsapp',
      name: 'WhatsApp Automation',
      description: 'Automated WhatsApp business messaging & chatbot',
      sacCode: '998314',
      setupCost: 20000,
      monthlyCost: 5000,
      priceType: 'hybrid',
      deliverables: [
        'WhatsApp Business API setup',
        'Automated reply flows',
        'Lead capture automation',
        'Broadcast campaigns',
        'CRM integration',
      ],
    },
    {
      id: 'auto_crm',
      name: 'CRM Automation',
      description: 'Automated customer relationship management workflows',
      sacCode: '998314',
      setupCost: 35000,
      monthlyCost: 8000,
      priceType: 'hybrid',
      deliverables: [
        'CRM setup & customization',
        'Lead pipeline automation',
        'Email/WhatsApp follow-up',
        'Deal stage automation',
        'Reporting dashboards',
      ],
    },
    {
      id: 'auto_lead',
      name: 'Lead Generation Automation',
      description: 'Automated multi-channel lead capture and nurturing',
      sacCode: '998314',
      setupCost: 25000,
      monthlyCost: 6000,
      priceType: 'hybrid',
      deliverables: [
        'Landing page with lead form',
        'Multi-channel lead capture',
        'Automated lead scoring',
        'Nurture email sequences',
        'Lead routing to sales',
      ],
    },
    {
      id: 'auto_chatbot',
      name: 'AI Chatbot',
      description: 'Intelligent AI-powered chatbot for your website/app',
      sacCode: '998314',
      setupCost: 50000,
      monthlyCost: 10000,
      priceType: 'hybrid',
      recommended: true,
      deliverables: [
        'Custom AI chatbot training',
        'Website/app integration',
        'Lead qualification',
        '24/7 automated support',
        'Human handoff feature',
        'Analytics dashboard',
      ],
    },
    {
      id: 'auto_email',
      name: 'Email Automation',
      description: 'Automated email marketing and drip campaigns',
      sacCode: '998314',
      setupCost: 15000,
      monthlyCost: 3000,
      priceType: 'hybrid',
      deliverables: [
        'Email platform setup',
        'Welcome sequence (5 emails)',
        'Drip campaigns',
        'Segmentation & targeting',
        'Performance reporting',
      ],
    },
    {
      id: 'auto_custom',
      name: 'Custom Automation',
      description: 'Tailored automation solution for your business process',
      sacCode: '998314',
      setupCost: 40000,
      monthlyCost: 8000,
      priceType: 'hybrid',
      deliverables: [
        'Process analysis & mapping',
        'Custom workflow automation',
        'API integrations',
        'Testing & deployment',
        'Team training',
      ],
    },
  ],
};

export const QUICK_PACKAGES = [
  {
    id: 'starter',
    name: 'Starter Business',
    tagline: 'Perfect for new businesses ready to launch',
    color: ['#3b82f6', '#06b6d4'],
    services: ['web_landing', 'dm_social'],
    totalPrice: 30000,
    monthlyPrice: 15000,
    highlights: ['Landing Page', 'Social Media (3 months)', 'Launch-ready in 2 weeks'],
  },
  {
    id: 'growth',
    name: 'Growth Package',
    tagline: 'Scale your business with integrated digital marketing',
    color: ['#7c3aed', '#3b82f6'],
    services: ['web_business', 'dm_seo', 'dm_ads'],
    totalPrice: 95000,
    monthlyPrice: 32000,
    highlights: ['Business Website', 'SEO (6 months)', 'Performance Ads', 'Full Analytics'],
    recommended: true,
  },
  {
    id: 'premium',
    name: 'Premium Domination',
    tagline: 'Own your market with full-stack digital presence',
    color: ['#f59e0b', '#ef4444'],
    services: ['web_business', 'dm_full', 'dm_seo', 'auto_chatbot'],
    totalPrice: 180000,
    monthlyPrice: 55000,
    highlights: ['Business Website', 'Full Marketing Suite', 'AI Chatbot', 'Dedicated Manager'],
  },
  {
    id: 'ecosystem',
    name: 'Full Digital Ecosystem',
    tagline: 'Complete technology & marketing transformation',
    color: ['#10b981', '#3b82f6'],
    services: ['app_both', 'web_custom', 'dm_full', 'auto_crm', 'auto_chatbot'],
    totalPrice: 850000,
    monthlyPrice: 63000,
    highlights: ['iOS + Android App', 'Custom Website', 'Full Marketing', 'CRM + AI Chatbot', 'End-to-End Automation'],
  },
];
